### ISSUE TITLE
Feature request: HIRS support Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by mwiseman32** [nsacyber/HIRS#7] opened 2018-09-17 20:07 UTC
Both ACA and and Provisioner* support for Ubuntu 18.04 LTS using repo tpm tools.

**Comment by iadgovuser26** [comment] 2018-09-17 20:34
The [HIRS build pages](https://github.com/nsacyber/HIRS/wiki/Hirs-build-guide) imply that building with Debian (and hence Ubuntu) is supported. However the section on building the TPM 2.0 Provisioner is missing instructions on building in Debian. I attempted to [build the TPM 2.0 Provisioner](https://github.com/nsacyber/HIRS/blob/master/HIRS_ProvisionerTPM2/README.md) on Ubuntu 18.04.1 and it failed.

Building via gradle currently attempts to build all projects s the TPM2 provisioner build will need to work. The package script utilizes gradle build so no packages can be built until the TPM2 provisioner builds.

**Comment by apldev3** [comment] 2018-09-17 21:16
@iadgovuser26 testing the Gradle build locally after some small updates. If it works, I'll be pushing up a merge request to at least get the build to work. Packaging into a Debian format will still need additional time, but it should stop overall build from failing.

**Comment by apldev3** [comment] 2018-09-19 01:38
With the latest push, we have a first crack at supporting Ubuntu 18.04 Code-wise. The next step will be to test the code in a live environment and, pending its success, then work to make the DEB package.

**Comment by iadgovuser26** [comment] 2018-09-19 18:48
I some trouble  building the HIRS_ProvisionerTPM2 project with this commit. 
Error was with cmake, at build/lib/cpr-src/opt/CMakelists.txt:60.
Had to delete the build directory , then it seemed to work fine.

**Comment by apldev3** [comment] 2018-09-21 20:40
With the current Merge Request that's up, Ubuntu building/packaging has been added, and support for Ubuntu 17.10 is confirmed, but there seems to be an issue with the performing the last major step of the provisioning process on Ubuntu 18.04. Will update as more becomes known.

**Comment by apldev3** [comment] 2018-10-02 21:46
Before closing this ticket, I feel an update is pertinent. Current investigation towards supporting Ubuntu 18.X releases out-of-the-box is not promising. There seems to be a bug(s) relating to the version of [tpm2-tools](https://github.com/tpm2-software/tpm2-tools) that is natively available to Ubuntu 18.X. As of 18.04 the version was updated to 2.1.0.

This particular version is known to have some bugs in major tools, and it has been suggested that users upgrade.

Unfortunately, this is a bit of a manual process, so I would propose as a last update to this task updating the build guide to provide a quick and easy means of downloading, building, and installing newer versions of tpm2-tools.

**Comment by apldev3** [comment] 2018-10-24 01:28
A MR is up that will finalize "support" for Ubuntu. That being said, a guide for installing the appropriate versions of Tpm2-tss, Tpm2-Tools, and Tpm2-Abrmd from source has been written and is being reviewed for publication. That guide will be necessary for those looking to install and use the TPM 2.0 Provisioner in Ubuntu environments.

**Closed** 2018-11-01 13:47 UTC
Labels: client, enhancement, server

**Comment by apldev3** [comment] 2018-11-01 13:50
The guide has been posted [here](https://github.com/nsacyber/HIRS/wiki/custom_TPM2SoftwareStack).
